### ISSUE TITLE
How to use double precision data type?

### ISSUE THREAD

**Issue by ruanjiaxing** [lboasso/oberonc#16]
It seemed oberonc define REAL as float internally. As Oberon-07 only has the REAL data type but not also SHORTREAL I think REAL should be mapped to double. Other Oberon-07 compiler like OBNC allows redefining the size of numeric data types via compiler options. BTW, I have no problem with the current implementation but only want to know how to use double precision number in oberonc (alongside with the single precision REAL).

**Comment by lboasso** [comment]
I agree that, in retrospect, `REAL` should have been mapped to a JVM `double`. I used `float` mainly because the Project Oberon's original compiler targets a processor with 32 bits floats and I wanted to be compatible. 
Making this change is not difficult, but requires some small adjustments in a bunch of places in the compiler. Would you be interested in creating a pull request with the fix? I can help you with the details.

**Comment by ruanjiaxing** [comment]
No. I want to keep the current implementation of yours as is because I don't have the ability to modify it. I used a quick find across all .java source of oberonc and found nothing about the mapping of REAL to float. So it must be in the .Mod source. I'm a totally noob about Oberon so I can't do anything with it.
I only asked to know how could I use java's double alongside with the current REAL in Oberon code. I didn't want to change the mapping of REAL to double.

**Comment by ruanjiaxing** [comment]
Your Oberon code is beautiful. But unfortunately I don't know Oberon enough to understand and modify it.

**Comment by lboasso** [comment]
Thanks for your kind words! Unfortunately there is currently no way to use the JVM's double data type in `oberonc`, because the current implementation hard code `REAL` to `float`. At this moment I don't have much free time to implement `double` support, but eventually I'll come back to this issue and address it, especially if more users need this feature

**Comment by ruanjiaxing** [comment]
I understand. I'm totally fine with float but if someday oberonc's REAL changed to double, it's much better! I will close this issue.
